spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/ServiceManagement
     username: root
     password: 1maiimaii
googleapi:
  key: ${GOOGLE_API_KEY}
store:
  latitude: ${STORE_LATITUDE}
  longitude: ${STORE_LONGITUDE}
